### ISSUE TITLE
Character Abilities should be listed in a consistent order

### ISSUE THREAD

**Issue by drumsetz** [jonBarcus/SoIaF_GM_Tools#17]
Currently, Character Abilities are listed in a way so that the last modified abilities are shown last.

These should probably be sorted in a consistent fashion.

**Comment by drumsetz** [comment]
Jon fixed this for show with the following commit:
166bec47f07bf2fcca4c8e99b21b7a6702cd1463

**Comment by drumsetz** [comment]
It still sorts based on modification time for edit -- but that seems to be quite a bit more difficult to handle due to the form_for usage. Might be able to use the @character_abilities instead of :abilities in the form_for... will investigate.

**Comment by drumsetz** [comment]
http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-fields_for

Using the record_object parameter, you can be explicit on the object being looped over in fields_for -- which allows us to sort the abilities before looping.

**Comment by jonBarcus** [comment]
I think you've successfully completed this.  Go ahead and close it if I'm correct!  :-p

**Comment by drumsetz** [comment]
Yeah, I agree. I should have finished the other half of this with that last change.
