### ISSUE TITLE
What should a CHARACTER have?

### ISSUE THREAD

**Issue by jonBarcus** [jonBarcus/SoIaF_GM_Tools#2]
Okay, so, I thought I'd open this up for discussion.  What should a character have in its table?
- user_id
- name
- surname
- house_id
- created_at (timestamp)
- updated_at (timestamp)

Now, what else should be include?

I had thought we should inlcude:
- height
- weight
- eye color
- hair color
- ethnicity? (Westerosi, Braavosi, Lysene, etc.)
- background? <--- they can enter their background information for the character

What are your thoughts?  Love your input.

**Comment by kirejm** [comment]
I'd make an ethnicity table and just make the character column a foreign key to that. That way we can add ethnicities and give 'em descriptions and stuff. (along with determine any possible ability changes, maybe?)

I'd also suggest adding a "description" field separate from the background since some people like writing both a background and a long description of the character's appearance.

**Comment by kirejm** [comment]
Oh, duh. And gender/age

**Comment by jonBarcus** [comment]
Cool.  What are your opinions on height/weight/eye color/hair color?  Should that be something a character has, or just have a description to allow for people to describe what their character looks like.

Now that I've typed that, I think that's what I'd like to go with.  _Not_ have hair/eye color and height/weight but rather have two columns for character history and character description.

Any other thoughts?

**Comment by drumsetz** [comment]
From a "thinking about the future" perspective, I'd recommend making
height/weight and eye/hair color separate fields (possibly allowing them to
be null if you don't want to require them) since these are things you could
use eventually as data - perhaps even just for sorting/searching purposes
when you have a lot of characters in your profile.

**Comment by jonBarcus** [comment]
@drumsetz That's a valid point...Though, while I can't see a reason for wanting to do that, as I type this...I can start see one.  :P

**Comment by jonBarcus** [comment]
Okay, so I'm just typing out my thinking right now...I'm thinking about making Eye/Hair and/or Height/Weight separate tables and adding the respective _id to the columns of character.  I _think_ that we should probably just make them fields...as seeding those tables might be more of a hassle than is necessary...also, I'm not sure we should have to worry about conversion...some people might want to use metrics...so I think we'll just leave height/weight as a field(string) and same for hair/eye color.

I'm leaning towards excluding hair/eye color as a field...though, including them might make people put some thought in to that when they're creating their character.  It might be a bit of positive social engineering to include them.

If either of you can weigh in soon, that'd be swell...otherwise I'll just have to make a decision and go forward.

**Comment by drumsetz** [comment]
For hair/eye color, you could make the separate table with options, which
will make the future search for characters easier since you won't have
different spellings, etc. But you won't necessarily need to seed the whole
table if you allow additions to the table of options (which could be a
future enhancement kind of thing, too).

**Comment by drumsetz** [comment]
I'd be inclined to agree with height weight being a straight string, though
trying to find your tall characters becomes difficult when you can't do a
numeric comparison on the height field. Perhaps a separate units field, but
that may be over thinking the problem.

**Comment by kirejm** [comment]
What's the definition of these terms in the manual? Is weight specified by
lbs or stone or something like that, and height by ft/inches?

2015-03-31 8:48 GMT-07:00 drumsetz notifications@github.com:

**Comment by jonBarcus** [comment]
That's a good question.

Actually, the book doesn't specify these four things at all.  I think their intention is to have physical details be described in a character description.

**Comment by jonBarcus** [comment]
Well, the book uses LBS and FT.

**Comment by jonBarcus** [comment]
Okay, for right now, I'm not going to include Height/Weight or Eye/Hair color in the character table.  That's something that can easily be added later.

**Comment by jonBarcus** [comment]
Alright, here's what the Character Table looks like now:

*id
*name
*surname
*age_id
*gender_id
*house_id
*description
*history
*user_id
*timestamps

I'm going to close this issue for the moment, and if someone wants to discuss further, please just open a new issue.

**Comment by kirejm** [comment]
Not really worth opening a new issue because I am cool with the resolution but why are we thinking of having a gender table? Is there something more complex than male/female?

-----Original Message-----

**Comment by drumsetz** [comment]
Do you need a separate entry for the actual age, or do you only want the
range stored (at least that's what I'm assuming the age_id will point to).

**Comment by jonBarcus** [comment]
To answer @kirejm , Gender for sorting purposes as well as a requirement for a drawback (Eunuch).  So, we need to have a recognized value.

@drumsetz So, we've got the age ranges in the book with their title (Young Adult, Venerable, etc.) as well as the starting xp and the like.  Which after re-reading your post you already know.  :p 

At the moment, we'll just let the users select the age category from the drop down...eventually, we'll have it built in to the app where they can type in a numeric value and then it will just know that the age (integer) entered is _middle age_ or _young adult_.

**Comment by kirejm** [comment]
Excellent but I want the option to select gender: Both.

-----Original Message-----

**Comment by jonBarcus** [comment]
Well, we could absolutely put something like that in...I'm seriously not opposed to it.  Maybe "unkown"?

I'm actually seriously asking you both.  What might be the best way to recognize transgender in the gender database?  I'll look in to it as well, but I'd love to hear any thoughts.

**Comment by kirejm** [comment]
Other/Custom? :/

-----Original Message-----

**Comment by drumsetz** [comment]
Custom could work as you could definitely allow additions to the gender
table that are then usable later... Requires some administration in car
people go crazy with additions, though.

You also need to remember to handle that in all code that references the
gender table.
