### ISSUE TITLE
User Account Creation - Unique E-mail

### ISSUE THREAD

**Issue by jonBarcus** [jonBarcus/SoIaF_GM_Tools#4]
We need to make it so the application checks against existing accounts by e-mail address and then prevent and prompt user about an account already being created for that e-mail address.

At the moment it allows for creation of user accounts of the same e-mail, which can cause problems for identifying characters/houses.

**Comment by jonBarcus** [comment]
We also need to make it so that it makes sure that a valid email is entered.

**Comment by kirejm** [comment]
I'll work on doing the validation stuff

**Comment by kirejm** [comment]
email addresses now being validated
